test:
  property: Hello from github test repo

spring:
  application:
    name: config-default
    #config default profile ie :8085/application/default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
